name: docs

on:
  push:
    branches: [main]

jobs:
  docs:
    name: Generate documentation
    if: github.repository == 'chromium/subspace'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Clang
        if: matrix.config.name == 'Ubuntu Nightly Clang'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 16 all

      - name: Configure
        run: |
          # Path to LLVM+Clang nightly that we have installed.
          export LLVM_DIR="/usr/lib/llvm-16/lib/cmake/llvm"
          export Clang_DIR="/usr/lib/llvm-16/lib/cmake/clang"

          sudo apt install build-essential cmake ninja-build
          cmake -G Ninja -B out -D CMAKE_EXPORT_COMPILE_COMMANDS=1
      
      - name: Documentation
        uses: hdoc/hdoc-github-action@v2
        with:
          compile-commands-path: out/compile_commands.json
          hdoc-api-key: ${{ secrets.HDOC_PROJECT_API_KEY }}
